name: Infra Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

permissions:
  actions: read
  security-events: write

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy IaC config scan
        uses: aquasecurity/trivy-action@0.32.0 # or @latest if version issues
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          output: trivy-iac-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-iac-results.sarif
